print(abs(-1))
sqrt(2)
ceiling(4.5)
ceiling(4.4)
floor(4.9)
trunc(3.1)
trunc(3.9)
round(3.14,digits=1)
signif(3.014,digits=2)
cos(1);sin(1);tan(1);acos(1);asin(1);atan(1)
log(2)
log10(2)
exp(10)
cat("PI Constant =", pi, "\n")
cat("PI Floor\t",floor(pi),"\n")
cat("PI ceiling\t",ceiling(pi),"\n")
cat("PI Rounded\t",round(pi,digits=2),"\n\n")
num <- 64
cat("Square Root of", num, "=", sqrt(num),"\n\n")
num <- (120*(pi/180))
cat ("Cosine of 120","=",cos(num),"\n\n")
num <- log(100)
cat("Log of",exp(num),"=",num,"\n")
num <- log10(100)
cat("Log10 of",exp(num),"=",num,"\n")